export const ADJUST_DELAY_DURATION = "ADJUST_DELAY_DURATION"
export const ADJUST_PRESENCE_DURATION = "ADJUST_PRESENCE_DURATION"
export const ADJUST_BRIGHTNESS_DURATION = "ADJUST_BRIGHTNESS_DURATION"
//just a convention to prevent spelling mistakes
export const SET_RELEVANCE = "SET_RELEVANCE"
export const SET_IMAGE_QUALITY = "SET_IMAGE_QUALITY"
export const SET_NUMBER_OF_IMAGES = "SET_NUMBER_OF_IMAGES"

export const SET_KEYWORD = "SET_KEYWORD"

export const SET_QUEUE = "SET_QUEUE"
export const COMMIT_CHANGES = "COMMIT_CHANGES"

export const SET_24HR = "SET_24HR"
export const SET_SECONDS = "SET_SECONDS"